/**
 * Chat Dialogue (spec addendum: the bot answers questions from history and
 * logs). Three parts, all bounded:
 *
 *  - intent router: deterministic pre-checks short-circuit the obvious
 *    (interrogatives about state = question, imperatives with a deliverable
 *    = task — zero added latency for the common paired-DM task), everything
 *    else goes through ONE smol-role oneshot returning
 *    question | task | other | mixed(+task line);
 *  - context assembler + answer composer: the reply is generated by a smol
 *    oneshot whose context is REAL sources only — live agent state (the
 *    СЕЙЧАС data), the current session transcript tail, the Team журнал,
 *    the watched chat's JSONL tail, recent Model Events when the question
 *    touches models/balances — versioned instruction template, grounded or
 *    honest refusal («в истории этого нет»), never file contents;
 *  - dialogue memory: last 10 bot↔user exchanges per chat, session-scoped
 *    (never persisted), so follow-ups («а до этого?») resolve.
 *
 * Module boundary: deletable. Callers (manager.ts DM path, watch-manager.ts
 * group path) treat routeIntent errors as "pre-dialogue behavior" and fall
 * back to the task/proposal flows unchanged.
 */

import { runOneshot, smolSelector } from "../oneshot-runner";
import { getAgentBridge } from "../omp-service";
import { listSessionMetas, readSessionEntries } from "../session-history";
import { teamJournalData } from "../omp-team/team-service";
import { loadModelsStore } from "../models/store";
import { readChatLogPage } from "./chat-log";
import { sanitizeOutbound } from "./format";
import type { SessionTracker } from "./session-tracker";

// ================================================== wiring

/** RemoteManager lends its tracker (diffstat / elapsed / last result) on init. */
let tracker: SessionTracker | null = null;

export function registerDialogueTracker(t: SessionTracker | null): void {
  tracker = t;
}

// ================================================== intent router

export type IntentVerdict =
  | { intent: "question" }
  | { intent: "task" }
  | { intent: "other" }
  | { intent: "mixed"; taskLine: string }
  | { intent: "error"; error: string };

/** versioned in code — bump the suffix when the wording changes */
const INTENT_SYSTEM_V1 =
  "You route messages addressed to a coding-agent bot. Reply with EXACTLY one line: " +
  '"QUESTION" (asks about the agent\'s status, history, past work or logs), ' +
  '"TASK" (orders concrete software work), ' +
  '"BOTH: <one short imperative line for the task half>" (contains a question AND a concrete task), or ' +
  '"OTHER" (greeting, thanks, noise, chit-chat).';

const INTERROGATIVE_RE =
  /^(что|чего|как|почему|поч|зачем|когда|кто|где|какой|какая|какие|каков|сколько|куда|откуда|можешь ли|есть ли|расскажи|покажи|what|how|why|when|who|where|which|what's|whats|show|status|статус)\b/i;

const IMPERATIVE_RE =
  /^(добавь|сделай|исправь|поправь|почини|создай|удали|убери|напиши|запусти|перезапусти|переименуй|обнови|замени|отрефактори|разверни|задеплой|подними|установи|настрой|add|fix|make|create|implement|write|run|update|refactor|rename|delete|remove|deploy|build|change|setup|set|install|configure)\b/i;

const NOISE_RE =
  /^(привет|здравствуй(те)?|хай|ку|спасибо|спс|благодарю|ок|окей|ладно|пока|hi|hello|hey|yo|thanks|thank you|ty|ok|okay|bye)[!.)\s]*$/i;

/** strip @mentions of the bot so patterns see the actual message head */
function normalize(text: string, botUsername?: string): string {
  let s = text.trim();
  if (botUsername) s = s.replace(new RegExp(`@${botUsername}\\b`, "gi"), " ");
  return s.replace(/\s+/g, " ").trim();
}

/**
 * Deterministic pre-check (spec §2): obvious cases never touch the model.
 * Returns null when ambiguous — including question+imperative mixes, which
 * need the model to extract the task line.
 */
export function preCheckIntent(text: string, botUsername?: string): IntentVerdict | null {
  const s = normalize(text, botUsername);
  if (!s) return { intent: "other" };
  if (NOISE_RE.test(s)) return { intent: "other" };
  // per-sentence scan: a question mark or interrogative head vs an imperative head
  const sentences = s.split(/[.!?;\n]+/).map((x) => x.trim()).filter(Boolean);
  const hasQ = /\?/.test(s) || INTERROGATIVE_RE.test(s);
  const hasImp = sentences.some((x) => IMPERATIVE_RE.test(x));
  if (hasQ && !hasImp) return { intent: "question" };
  if (hasImp && !hasQ) return { intent: "task" };
  return null; // mixed or unclear → smol
}

/** tolerate spinner lines, quotes and case around the verdict */
function parseIntent(stdout: string): IntentVerdict {
  const lines = stdout
    .split(/\r?\n/)
    .map((l) => l.trim().replace(/^["'«]|["'»]$/g, "").trim())
    .filter(Boolean);
  for (let i = lines.length - 1; i >= 0; i--) {
    const l = lines[i];
    const both = l.match(/^BOTH:\s*(.+)$/i);
    if (both) return { intent: "mixed", taskLine: both[1].trim().slice(0, 200) };
    if (/^QUESTION[.!]?$/i.test(l)) return { intent: "question" };
    if (/^TASK[.!]?$/i.test(l)) return { intent: "task" };
    if (/^OTHER[.!]?$/i.test(l)) return { intent: "other" };
  }
  // an unparseable verdict is an error — callers fall back to pre-dialogue behavior
  return { intent: "error", error: `unparseable intent verdict: ${lines[lines.length - 1] ?? "(empty)"}` };
}

/**
 * Route one addressed message: pre-check first, smol classification for the
 * rest. `contextLines` = up to 5 recent chat messages (spec §2).
 */
export async function routeIntent(
  text: string,
  contextLines: string[],
  botUsername?: string,
): Promise<IntentVerdict> {
  const pre = preCheckIntent(text, botUsername);
  if (pre) return pre;
  const prompt =
    (contextLines.length ? "chat context:\n" + contextLines.join("\n") + "\n\n" : "") +
    `MESSAGE: ${normalize(text, botUsername).slice(0, 600)}`;
  const res = await runOneshot({
    system: INTENT_SYSTEM_V1,
    prompt,
    model: smolSelector(),
    timeoutMs: 45_000,
  });
  if (!res.ok) return { intent: "error", error: res.error };
  return parseIntent(res.stdout);
}

// ================================================== dialogue memory

interface Exchange {
  asker: string;
  q: string;
  a: string;
  at: number;
}

const MEMORY_CAP = 10;
/** `${botId}:${chatId}` → last exchanges; session-scoped, never persisted */
const memory = new Map<string, Exchange[]>();

function memoryFor(botId: string, chatId: number): Exchange[] {
  return memory.get(`${botId}:${chatId}`) ?? [];
}

function remember(botId: string, chatId: number, ex: Exchange): void {
  const key = `${botId}:${chatId}`;
  const list = memory.get(key) ?? [];
  list.push(ex);
  if (list.length > MEMORY_CAP) list.shift();
  memory.set(key, list);
}

// ================================================== context assembler

const hhmm = (at: number): string => {
  const d = new Date(at);
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
};

const oneLine = (s: string, cap: number): string =>
  sanitizeOutbound(s).replace(/\s+/g, " ").trim().slice(0, cap);

const MODEL_TOPIC_RE = /(модел|model|баланс|balance|кредит|credit|swap|своп|квот|quota|лимит|limit|провайдер|provider|профил|profile)/i;

/** REAL sources only (spec §2) — each section is honest, capped, plain text */
function assembleContext(args: { botId: string; chatId: number; isGroup: boolean; question: string }): string {
  const bridge = getAgentBridge();
  const sections: string[] = [];

  // 1. live agent state — the data the СЕЙЧАС zone shows
  {
    const lines: string[] = [];
    const root = bridge.getRoot();
    const st = bridge.getStatus();
    if (!root) lines.push("no workspace open, agent not running");
    else {
      const state = !st ? "no session" : st.state === "tool" && st.tool ? `running tool: ${st.tool}` : st.state;
      lines.push(`workspace: ${root}`);
      lines.push(`agent state: ${state}`);
      const phases = bridge.getTodoPhases();
      let done = 0, total = 0;
      const active: string[] = [];
      for (const p of phases)
        for (const tk of p.tasks) {
          total++;
          if (tk.status === "completed") done++;
          if (tk.status === "in_progress") active.push(tk.content);
        }
      if (total) lines.push(`todo: ${done}/${total} done${active.length ? `, now: ${active.join("; ").slice(0, 160)}` : ""}`);
      if (tracker) {
        if (tracker.elapsedMs > 0) lines.push(`elapsed on current task: ${Math.round(tracker.elapsedMs / 60000)}m`);
        const stats = tracker.stats();
        if (stats.length)
          lines.push("files touched this session: " + stats.slice(0, 12).map((s) => `${s.path} +${s.add} −${s.del}`).join(", "));
        if (tracker.lastFinalText) lines.push(`last agent answer: ${oneLine(tracker.lastFinalText, 400)}`);
      }
    }
    sections.push("=== LIVE STATE ===\n" + lines.join("\n"));
  }

  // 2. current/last session transcript tail (~30 turns, markers stripped)
  {
    const root = bridge.getRoot();
    if (root) {
      try {
        const metas = listSessionMetas(root);
        if (metas.length) {
          const entries = readSessionEntries(metas[0].file);
          const turns = entries
            .filter((e) => e.kind === "user" || e.kind === "assistant")
            .slice(-30)
            .map((e) => `[${hhmm(e.at)}] ${e.kind === "user" ? "user" : "agent"}: ${oneLine(e.text ?? "", 220)}`)
            .filter((l) => !/: $/.test(l));
          if (turns.length) sections.push("=== SESSION TRANSCRIPT (tail) ===\n" + turns.join("\n"));
        }
      } catch {
        /* transcript unavailable — the section is simply absent */
      }
    }
  }

  // 3. Team журнал — milestones, slices, verification result
  {
    const j = teamJournalData();
    if (j) {
      const lines = [
        `phase: ${j.phase}`,
        j.goal ? `goal: ${oneLine(j.goal, 160)}` : "",
        j.planSummary ? `plan: ${oneLine(j.planSummary, 220)}` : "",
        ...j.slices.map((s) => `slice ${s.id} «${oneLine(s.title, 60)}» ${s.state} (${s.worker}) +${s.add} −${s.del}`),
        ...j.feed.map((f) => `[${hhmm(f.at)}] ${f.author}: ${oneLine(f.text, 120)}`),
        j.report ? `report: ${oneLine(j.report, 400)}` : "",
      ].filter(Boolean);
      sections.push("=== TEAM RUN (журнал) ===\n" + lines.join("\n"));
    }
  }

  // 4. this chat's JSONL log tail (watched groups only)
  if (args.isGroup) {
    const entries = readChatLogPage(args.botId, args.chatId, undefined, 50).reverse();
    if (entries.length)
      sections.push(
        "=== CHAT LOG (tail) ===\n" +
          entries.map((e) => `[${hhmm(e.time)}] ${e.author}: ${oneLine(e.text, 160)}`).join("\n"),
      );
  }

  // 5. recent Model Events — only when the question touches models/balances
  if (MODEL_TOPIC_RE.test(args.question)) {
    const events = loadModelsStore().events.slice(-10);
    if (events.length)
      sections.push(
        "=== MODEL EVENTS ===\n" +
          events.map((e) => `[${hhmm(e.time)}] ${e.kind}: ${oneLine(e.detail, 140)} (${e.origin})`).join("\n"),
      );
  }

  // 6. dialogue memory — resolves follow-ups («а до этого?»)
  {
    const mem = memoryFor(args.botId, args.chatId);
    if (mem.length)
      sections.push(
        "=== EARLIER IN THIS DIALOGUE ===\n" +
          mem.map((x) => `${x.asker} asked: ${oneLine(x.q, 140)}\nbot answered: ${oneLine(x.a, 200)}`).join("\n"),
      );
  }

  // budget: drop the chattiest middle sections first if we blow the cap
  let ctx = sections.join("\n\n");
  const CAP = 7000;
  if (ctx.length > CAP) {
    const trimmed = sections.map((s) =>
      s.startsWith("=== CHAT LOG") || s.startsWith("=== SESSION TRANSCRIPT")
        ? s.split("\n").slice(0, 18).join("\n")
        : s,
    );
    ctx = trimmed.join("\n\n").slice(0, CAP);
  }
  return ctx;
}

// ================================================== answer composer

/** versioned in code — bump the suffix when the wording changes */
const ANSWER_SYSTEM_V1 =
  "You are the status voice of the OMP IDE coding agent, replying as its bot in a chat. " +
  "Answer the user's question STRICTLY from the CONTEXT sections below — they are the only truth. " +
  "Reply in the user's language (Russian question → Russian answer). 1-4 sentences, plain text: " +
  "no markdown headings, no code blocks, no file contents, no secrets or tokens. Be concrete — name " +
  "files, diffstats (+N −M), elapsed times and slice ids when the context has them. If the context " +
  "does not contain the answer, say plainly that the history has no record of it (Russian: " +
  "«в истории этого нет»), and when helpful add that the full record is in the IDE's History Browser. " +
  "Never invent facts, numbers or file names.";

export async function answerQuestion(args: {
  botId: string;
  chatId: number;
  question: string;
  asker: string;
  isGroup: boolean;
}): Promise<{ ok: true; answer: string } | { ok: false; error: string }> {
  const context = assembleContext(args);
  const res = await runOneshot({
    system: ANSWER_SYSTEM_V1,
    prompt: `${context}\n\nQUESTION from @${args.asker}: ${args.question.slice(0, 500)}`,
    model: smolSelector(),
    timeoutMs: 60_000,
  });
  if (!res.ok) return { ok: false, error: res.error };
  // last non-spinner paragraph, unquoted, capped — Message economy: ONE short reply
  const answer = sanitizeOutbound(res.stdout)
    .trim()
    .replace(/^["'«]|["'»]$/g, "")
    .trim()
    .slice(0, 900);
  if (!answer) return { ok: false, error: "empty answer from oneshot" };
  remember(args.botId, args.chatId, { asker: args.asker, q: args.question, a: answer, at: Date.now() });
  return { ok: true, answer };
}
